//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace belpost_checker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("belpost_checker.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;{2}&quot;&gt;&lt;td&gt;{0}&lt;/td&gt;&lt;td&gt;{1}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        internal static string EmailBodyInner {
            get {
                return ResourceManager.GetString("EmailBodyInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;style&gt;
        ///    table {{color: grey; font-weight: bold;}}
        ///    .changed {{color:green;}}
        ///  &lt;/style&gt;
        ///  &lt;p&gt;Статус посылки &apos;{0}&apos; с номером слежения &apos;{1}&apos; изменился&lt;/p&gt;
        ///  &lt;table&gt;
        ///#INNER_TEMPLATE#
        ///  &lt;/table&gt;
        ///  &lt;p&gt;Информация взята отсюда: &lt;a href=&quot;http://search.belpost.by/#{1}&quot;&gt;http://search.belpost.by/#{1}&lt;/a&gt;&lt;/p&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string EmailBodyOuter {
            get {
                return ResourceManager.GetString("EmailBodyOuter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменился статус посылки &apos;{0}&apos; с номером слежения &apos;{1}&apos;.
        /// </summary>
        internal static string StatusChancedEmailSubject {
            get {
                return ResourceManager.GetString("StatusChancedEmailSubject", resourceCulture);
            }
        }
    }
}
