//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posttrack.BLL.Tests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3" +
            ".org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n\r\n<html xmlns=\"http://www.w3.org/1" +
            "999/xhtml\" >\r\n<head><title>\r\n\tПоиск отправлений\r\n</title><link rel=\"icon\" href=\"" +
            "Resources/favicon.ico\" type=\"image/x-icon\" />\r\n    <style type=\"text/css\">\r\n\r\n\r\n" +
            "body {\r\n    background: #FFF url(\"/Resources/bgr.png\") repeat-x;\r\n}\r\n\r\n    </sty" +
            "le>\r\n</head>\r\n<body>\r\n    <form name=\"form1\" method=\"post\" action=\"searchRu.aspx" +
            "\" id=\"form1\">\r\n<input type=\"hidden\" name=\"__VIEWSTATE\" id=\"__VIEWSTATE\" value=\"/" +
            "wEPDwULLTE1NTQ1NzEwNDQPZBYCAgMPZBYCAgkPDxYCHgdWaXNpYmxlZ2QWBgIBDzwrAA0BAA8WBB4LX" +
            "yFEYXRhQm91bmRnHgtfIUl0ZW1Db3VudAIFZBYCZg9kFgwCAQ9kFgZmD2QWAgIBDw8WAh4EVGV4dAUTM" +
            "jAxNS0xMS0wNyAxNDo0MDowMGRkAgEPZBYCAgEPDxYCHwMFRdCf0L7Qu9GD0YfQtdC90LjQtSDQvtGC0" +
            "L/RgNCw0LLQu9C10L3QuNGPINC+0YIg0L7RgtC/0YDQsNCy0LjRgtC10LvRj2RkAgIPDxYCHwMFBzUxO" +
            "DEwMypkZAICD2QWBmYPZBYCAgEPDxYCHwMFEzIwMTUtMTEtMjQgMTU6MzU6MTFkZAIBD2QWAgIBDw8WA" +
            "h8DBULQn9C+0YHRgtGD0L/QuNC70L4g0LIg0YPRh9Cw0YHRgtC+0Log0L7QsdGA0LDQsdC+0YLQutC4I" +
            "NC/0L7Rh9GC0YtkZAICDw8WAh8DBQpNSU5TSyBQSSAyZGQCAw9kFgZmD2QWAgIBDw8WAh8DBRMyMDE1L" +
            "TExLTI0IDIwOjExOjQ0ZGQCAQ9kFgICAQ8PFgIfAwWsAdCf0YDQvtGF0L7QttC00LXQvdC40LUg0L/Qv" +
            "iDRgtCw0LzQvtC20LXQvdC90L7QuSDQt9C+0L3QtSAo0YHQvC4gPGEgaHJlZj0iaHR0cDovL2RlY2xhc" +
            "mF0aW9uLmJlbHBvc3QuYnkvc2VhcmNoLmFzcHg/c2VhcmNoPVJGMTA5OTU5NzY0Q04iPmh0dHA6Ly9kZ" +
            "WNsYXJhdGlvbi5iZWxwb3N0LmJ5PC9hPilkZAICDw8WAh8DBQpNSU5TSyBQSSAyZGQCBA9kFgZmD2QWA" +
            "gIBDw8WAh8DBRMyMDE1LTExLTI3IDEzOjA1OjAwZGQCAQ9kFgICAQ8PFgIfAwUf0J/QvtC/0YvRgtC60" +
            "LAg0LLRgNGD0YfQtdC90LjRj2RkAgIPDxYCHwMFCk1JTlNLIC0gMzRkZAIFD2QWBmYPZBYCAgEPDxYCH" +
            "wMFEzIwMTUtMTEtMjcgMjI6Mjc6MDBkZAIBD2QWAgIBDw8WAh8DBQ7QktGA0YPRh9C10L3QvmRkAgIPD" +
            "xYCHwMFCk1JTlNLIC0gMzRkZAIGDw8WAh8AaGRkAgMPDxYCHwBnZGQCBQ88KwANAQAPFgQfAWcfAgIEZ" +
            "BYCZg9kFgoCAQ9kFgRmD2QWAgIBDw8WAh8DBRMyNy4xMS4yMDE1IDA2OjMyOjE3ZGQCAQ9kFgICAQ8PF" +
            "gIfAwWnATA4LiDQn9C10YDQtdC00LDQvdC+INC40LcgKDxhIGhyZWY9Imh0dHA6Ly96aXAuYmVscG9zd" +
            "C5ieS96aXBfY29kZS8yMDA0MDAiPjIwMDQwMDwvYT4pICDQsiAoPGEgaHJlZj0iaHR0cDovL3ppcC5iZ" +
            "Wxwb3N0LmJ5L3ppcF9jb2RlLzIyMDAzNCI+MjIwMDM0PC9hPikg0JzQuNC90YHQuiAtIDM0ZGQCAg9kF" +
            "gRmD2QWAgIBDw8WAh8DBRMyNy4xMS4yMDE1IDA5OjI0OjAwZGQCAQ9kFgICAQ8PFgIfAwWTATA2LiDQn" +
            "9C+0YHRgtGD0L/QuNC70L4g0LIg0YPRh9Cw0YHRgtC+0Log0L7QsdGA0LDQsdC+0YLQutC4INC/0L7Rh" +
            "9GC0YsgKDxhIGhyZWY9Imh0dHA6Ly96aXAuYmVscG9zdC5ieS96aXBfY29kZS8yMjAwMzQiPjIyMDAzN" +
            "DwvYT4pINCc0LjQvdGB0LogLSAzNGRkAgMPZBYEZg9kFgICAQ8PFgIfAwUTMjcuMTEuMjAxNSAxMDowN" +
            "TowMGRkAgEPZBYCAgEPDxYCHwMFcDA5LiDQn9C+0L/Ri9GC0LrQsCDQtNC+0YHRgtCw0LLQutC4ICg8Y" +
            "SBocmVmPSJodHRwOi8vemlwLmJlbHBvc3QuYnkvemlwX2NvZGUvMjIwMDM0Ij4yMjAwMzQ8L2E+KSDQn" +
            "NC40L3RgdC6IC0gMzRkZAIED2QWBGYPZBYCAgEPDxYCHwMFEzI3LjExLjIwMTUgMTk6Mjc6MDBkZAIBD" +
            "2QWAgIBDw8WAh8DBXUxMC4g0JTQvtGB0YLQsNCy0LvQtdC90L4sINCy0YDRg9GH0LXQvdC+ICg8YSBoc" +
            "mVmPSJodHRwOi8vemlwLmJlbHBvc3QuYnkvemlwX2NvZGUvMjIwMDM0Ij4yMjAwMzQ8L2E+KSDQnNC40" +
            "L3RgdC6IC0gMzRkZAIFDw8WAh8AaGRkGAMFHl9fQ29udHJvbHNSZXF1aXJlUG9zdEJhY2tLZXlfXxYBB" +
            "QlJQnRuQnVuZXIFCUdyaWRJbmZvMA88KwAKAQgCAWQFCEdyaWRJbmZvDzwrAAoBCAIBZIG3RJ4elpV/b" +
            "YcBHIisdC9v4WkJ\" />\r\n\r\n<input type=\"hidden\" name=\"__VIEWSTATEGENERATOR\" id=\"__VI" +
            "EWSTATEGENERATOR\" value=\"F0F1CCD9\" />\r\n<input type=\"hidden\" name=\"__EVENTVALIDAT" +
            "ION\" id=\"__EVENTVALIDATION\" value=\"/wEWBALmx5VpAsmT79MDAvacrMEOAsWd9e4KxfszZZ1fh" +
            "BP2Q6t2TnpAarXKLvU=\" />\r\n    <div>\r\n    \r\n    <p style=\"margin-left: 250px\">\r\n  " +
            "  <input type=\"image\" name=\"IBtnBuner\" id=\"IBtnBuner\" src=\"Resources/ban.png\" bo" +
            "rder=\"0\" />\r\n    \r\n        <br />\r\n        <p style=\"margin-left: 250px\">\r\n     " +
            "   \r\n\t\t<br />\r\n            <font  style=\"font-size:18pt;line-height:115%;font-fa" +
            "mily:&quot;Times New Roman&quot;\" \r\n                color=\"Black\">&nbsp;&nbsp;&n" +
            "bsp; <b>Слежение за почтовыми отправлениями</b></font>\r\n                \r\n      " +
            "  <p style=\"margin-left: 250px; width: 817px;\">\r\n        \r\n\t\t    <font  style=\"f" +
            "ont-size:13.5pt;line-height:115%;font-family:&quot;Times New Roman&quot;\" \r\n    " +
            "            color=\"Black\">&nbsp;&nbsp;&nbsp; По вопросам таможенных операций и н" +
            "ачислениям таможенных платежей обращаться на официальный сайт Минской региональн" +
            "ой таможни <a href=\"http://mrt.customs.gov.by/\" target=\"_blank\">mrt.customs.gov." +
            "by</a> </font>\r\n                        \r\n        <p style=\"margin-left: 250px; " +
            "width: 817px;\">\r\n        \r\n\t\t    <font  style=\"font-size:13.5pt;line-height:115%" +
            ";font-family:&quot;Times New Roman&quot;\" \r\n                color=\"Black\">&nbsp;" +
            "&nbsp;&nbsp; Посмотреть информацию о статусах почтовых отправлений вы можете <a " +
            "href=\"http://www.belpost.by/info/statusy/\" target=\"_blank\">\r\n            <b>здес" +
            "ь</b></a> </font>\r\n                                \r\n        <p style=\"margin-le" +
            "ft: 250px; width: 817px;\">\r\n        \r\n\t\t    <font  style=\"font-size:13.5pt;line-" +
            "height:115%;font-family:&quot;Times New Roman&quot;\" \r\n                color=\"Bl" +
            "ack\">&nbsp;&nbsp;&nbsp; <b>Уважаемые клиенты!</b>\r\nВы можете оформить перенаправ" +
            "ление международного регистрируемого почтового отправления для получения его в п" +
            "ункте почтовой связи по приему и выдаче почтовых отправлений. Перенаправление мо" +
            "жно оформить <a href=\"http://declaration.belpost.by/redirection.aspx\" target=\"_b" +
            "lank\">\r\n            <b>здесь</b></a> . Услуга по перенаправлению доступна только" +
            " до момента поступления почтового отправления на таможенный контроль в учреждени" +
            "е международного почтового обмена.</font>\r\n        <p style=\"margin-left: 250px;" +
            " width: 817px;\">\r\n        \r\n\t\t    <font  style=\"font-size:13.5pt;line-height:115" +
            "%;font-family:&quot;Times New Roman&quot;\" \r\n                color=\"Black\">&nbsp" +
            ";&nbsp;&nbsp; <b>Уважаемые клиенты!</b>\r\nВ случае получения записи по Вашему отп" +
            "равлению: «<b>Для передачи в таможню необходимо уточнить данные</b>» требуется з" +
            "аполнить прилагаемую форму - «Форма для заполнения», в противном случае отправле" +
            "ние будет возвращено. </font>\r\n                        \r\n        <p style=\"margi" +
            "n-left: 250px; width: 817px;\">\r\n        \r\n\t\t    <font  style=\"font-size:13.5pt;l" +
            "ine-height:115%;font-family:&quot;Times New Roman&quot;\" \r\n                color" +
            "=\"Black\">&nbsp;&nbsp;&nbsp; Данные необходимо вносить ТОЛЬКО один раз. Неоднокра" +
            "тно введенные данные замедляют процесс обработки. Статус посылки изменяется посл" +
            "е обработки информации сотрудниками таможенного отдела.</font>\r\n                " +
            "        \r\n        <p style=\"margin-left: 250px\">\r\n        \r\n\t\t    <font  style=\"" +
            "font-size:16pt;line-height:115%;font-family:&quot;Times New Roman&quot;\" \r\n     " +
            "           color=\"Black\">&nbsp;</font><p style=\"margin-left: 250px\">\r\n        \r\n" +
            "\t\t    <span id=\"Label1\" color=\"Black\" style=\"display:inline-block;font-size:13.5" +
            "pt;line-height:115%;font-family:\"Times New Roman\"\"><font size=\"5\">Введите номер " +
            "отправления:</font></span>\r\n            <input name=\"TxtNumPos\" type=\"text\" valu" +
            "e=\"RF109959764CN\" id=\"TxtNumPos\" style=\"margin-top: 0px\" />\r\n            <input " +
            "type=\"submit\" name=\"BtnSearch\" value=\"Поиск\" id=\"BtnSearch\" />\r\n            \r\n  " +
            "          <p style=\"margin-left: 250px\">\r\n        \r\n\t\t        &nbsp;<div id=\"Pan" +
            "el2\" style=\"margin-left: 250px\">\r\n\t\r\n                <div>\r\n\t\t<table class=\"marg" +
            "in-left: 250px\'\" cellspacing=\"0\" cellpadding=\"4\" rules=\"cols\" bordercolor=\"#DEDF" +
            "DE\" border=\"1\" id=\"GridInfo\" width=\"754\" bgcolor=\"White\">\r\n\t\t\t<tr bgcolor=\"White" +
            "\">\r\n\t\t\t\t<th scope=\"col\"><font face=\"Times New Roman\" color=\"Black\" size=\"4\"><b>Д" +
            "ата</b></font></th><th scope=\"col\"><font face=\"Times New Roman\" color=\"Black\" si" +
            "ze=\"4\"><b>Событие</b></font></th><th scope=\"col\"><font face=\"Times New Roman\" co" +
            "lor=\"Black\" size=\"4\"><b>Офис</b></font></th>\r\n\t\t\t</tr><tr bgcolor=\"#8BE3FF\">\r\n\t\t" +
            "\t\t<td><font face=\"Times New Roman\" color=\"Black\" size=\"4\">\r\n                    " +
            "            <span id=\"GridInfo_ctl02_Label2\" style=\"display:inline-block;\">2015-" +
            "11-07 14:40:00</span>\r\n                            </font></td><td><font face=\"T" +
            "imes New Roman\" color=\"Black\" size=\"4\">\r\n                                <span i" +
            "d=\"GridInfo_ctl02_Label1\">Получение отправления от отправителя</span>\r\n         " +
            "                   </font></td><td><font face=\"Times New Roman\" color=\"Black\" si" +
            "ze=\"4\">518103*</font></td>\r\n\t\t\t</tr><tr bgcolor=\"White\">\r\n\t\t\t\t<td><font face=\"Ti" +
            "mes New Roman\" color=\"Black\" size=\"4\">\r\n                                <span id" +
            "=\"GridInfo_ctl03_Label2\" style=\"display:inline-block;\">2015-11-24 15:35:11</span" +
            ">\r\n                            </font></td><td><font face=\"Times New Roman\" colo" +
            "r=\"Black\" size=\"4\">\r\n                                <span id=\"GridInfo_ctl03_La" +
            "bel1\">Поступило в участок обработки почты</span>\r\n                            </" +
            "font></td><td><font face=\"Times New Roman\" color=\"Black\" size=\"4\">MINSK PI 2</fo" +
            "nt></td>\r\n\t\t\t</tr><tr bgcolor=\"#8BE3FF\">\r\n\t\t\t\t<td><font face=\"Times New Roman\" c" +
            "olor=\"Black\" size=\"4\">\r\n                                <span id=\"GridInfo_ctl04" +
            "_Label2\" style=\"display:inline-block;\">2015-11-24 20:11:44</span>\r\n             " +
            "               </font></td><td><font face=\"Times New Roman\" color=\"Black\" size=\"" +
            "4\">\r\n                                <span id=\"GridInfo_ctl04_Label1\">Прохождени" +
            "е по таможенной зоне (см. <a href=\"http://declaration.belpost.by/search.aspx?sea" +
            "rch=RF109959764CN\">http://declaration.belpost.by</a>)</span>\r\n                  " +
            "          </font></td><td><font face=\"Times New Roman\" color=\"Black\" size=\"4\">MI" +
            "NSK PI 2</font></td>\r\n\t\t\t</tr><tr bgcolor=\"White\">\r\n\t\t\t\t<td><font face=\"Times Ne" +
            "w Roman\" color=\"Black\" size=\"4\">\r\n                                <span id=\"Grid" +
            "Info_ctl05_Label2\" style=\"display:inline-block;\">2015-11-27 13:05:00</span>\r\n   " +
            "                         </font></td><td><font face=\"Times New Roman\" color=\"Bla" +
            "ck\" size=\"4\">\r\n                                <span id=\"GridInfo_ctl05_Label1\">" +
            "Попытка вручения</span>\r\n                            </font></td><td><font face=" +
            "\"Times New Roman\" color=\"Black\" size=\"4\">MINSK - 34</font></td>\r\n\t\t\t</tr><tr bgc" +
            "olor=\"#8BE3FF\">\r\n\t\t\t\t<td><font face=\"Times New Roman\" color=\"Black\" size=\"4\">\r\n " +
            "                               <span id=\"GridInfo_ctl06_Label2\" style=\"display:i" +
            "nline-block;\">2015-11-27 22:27:00</span>\r\n                            </font></t" +
            "d><td><font face=\"Times New Roman\" color=\"Black\" size=\"4\">\r\n                    " +
            "            <span id=\"GridInfo_ctl06_Label1\">Вручено</span>\r\n                   " +
            "         </font></td><td><font face=\"Times New Roman\" color=\"Black\" size=\"4\">MIN" +
            "SK - 34</font></td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t</div>\r\n            \r\n              " +
            "  <br />\r\n                <span id=\"Label49\" style=\"font-size:16pt;line-height:1" +
            "15%;font-family:\"Times New Roman\"\"><font size=\"6\">Прохождение по стране:</font><" +
            "/span>\r\n            \r\n                <div>\r\n\t\t<table class=\"margin-left: 250px\'" +
            "\" cellspacing=\"0\" cellpadding=\"4\" rules=\"cols\" bordercolor=\"#DEDFDE\" border=\"1\" " +
            "id=\"GridInfo0\" width=\"754\" bgcolor=\"White\">\r\n\t\t\t<tr bgcolor=\"White\">\r\n\t\t\t\t<th sc" +
            "ope=\"col\"><font face=\"Times New Roman\" color=\"Black\" size=\"4\"><b>Дата</b></font>" +
            "</th><th scope=\"col\"><font face=\"Times New Roman\" color=\"Black\" size=\"4\"><b>Собы" +
            "тие</b></font></th>\r\n\t\t\t</tr><tr bgcolor=\"#8BE3FF\">\r\n\t\t\t\t<td><font face=\"Times N" +
            "ew Roman\" color=\"Black\" size=\"4\">\r\n                                <span id=\"Gri" +
            "dInfo0_ctl02_Label2\" style=\"display:inline-block;\">27.11.2015 06:32:17</span>\r\n " +
            "                           </font></td><td><font face=\"Times New Roman\" color=\"B" +
            "lack\" size=\"4\">\r\n                                <span id=\"GridInfo0_ctl02_Label" +
            "1\">08. Передано из (<a href=\"http://zip.belpost.by/zip_code/200400\">200400</a>) " +
            " в (<a href=\"http://zip.belpost.by/zip_code/220034\">220034</a>) Минск - 34</span" +
            ">\r\n                            </font></td>\r\n\t\t\t</tr><tr bgcolor=\"White\">\r\n\t\t\t\t<" +
            "td><font face=\"Times New Roman\" color=\"Black\" size=\"4\">\r\n                       " +
            "         <span id=\"GridInfo0_ctl03_Label2\" style=\"display:inline-block;\">27.11.2" +
            "015 09:24:00</span>\r\n                            </font></td><td><font face=\"Tim" +
            "es New Roman\" color=\"Black\" size=\"4\">\r\n                                <span id=" +
            "\"GridInfo0_ctl03_Label1\">06. Поступило в участок обработки почты (<a href=\"http:" +
            "//zip.belpost.by/zip_code/220034\">220034</a>) Минск - 34</span>\r\n               " +
            "             </font></td>\r\n\t\t\t</tr><tr bgcolor=\"#8BE3FF\">\r\n\t\t\t\t<td><font face=\"T" +
            "imes New Roman\" color=\"Black\" size=\"4\">\r\n                                <span i" +
            "d=\"GridInfo0_ctl04_Label2\" style=\"display:inline-block;\">27.11.2015 10:05:00</sp" +
            "an>\r\n                            </font></td><td><font face=\"Times New Roman\" co" +
            "lor=\"Black\" size=\"4\">\r\n                                <span id=\"GridInfo0_ctl04" +
            "_Label1\">09. Попытка доставки (<a href=\"http://zip.belpost.by/zip_code/220034\">2" +
            "20034</a>) Минск - 34</span>\r\n                            </font></td>\r\n\t\t\t</tr>" +
            "<tr bgcolor=\"White\">\r\n\t\t\t\t<td><font face=\"Times New Roman\" color=\"Black\" size=\"4" +
            "\">\r\n                                <span id=\"GridInfo0_ctl05_Label2\" style=\"dis" +
            "play:inline-block;\">27.11.2015 19:27:00</span>\r\n                            </fo" +
            "nt></td><td><font face=\"Times New Roman\" color=\"Black\" size=\"4\">\r\n              " +
            "                  <span id=\"GridInfo0_ctl05_Label1\">10. Доставлено, вручено (<a " +
            "href=\"http://zip.belpost.by/zip_code/220034\">220034</a>) Минск - 34</span>\r\n    " +
            "                        </font></td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t</div>\r\n           " +
            " \r\n                <br />\r\n                \r\n            \r\n            \r\n</div>\r" +
            "\n        \r\n    </div>\r\n    </form>\r\n    <p style=\"margin-left: 250px\">\r\n        " +
            "\r\n\t\t    <font  style=\"font-size:16pt;line-height:115%;font-family:&quot;Times Ne" +
            "w Roman&quot;\" \r\n                color=\"Black\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nb" +
            "sp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp" +
            ";&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&" +
            "nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nb" +
            "sp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp" +
            ";&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Внимание! </font>\r\n<p style=\"margin-left: " +
            "250px; width: 811px;\">\r\n        \r\n\t\t    <font  style=\"font-size:13.5pt;line-heig" +
            "ht:115%;font-family:&quot;Times New Roman&quot;\" \r\n                color=\"Black\"" +
            ">&nbspНомер отправления вводится - латинским шрифтом, без пробелов. <p style=\"ma" +
            "rgin-left: 250px; width: 811px;\">\r\n        \r\n\t\t    <font  style=\"font-size:13.5p" +
            "t;line-height:115%;font-family:&quot;Times New Roman&quot;\" \r\n                co" +
            "lor=\"Black\">&nbsp;Обращаем Ваше внимание, что все международные посылки доставля" +
            "ются по адресу получателя. В случае отсутствия адресата, в почтовом ящике оставл" +
            "яется извещение о поступлении международного отправления. </font>\r\n    <p style=" +
            "\"margin-left: 250px; width: 811px;\">\r\n        \r\n\t\t    <font  style=\"font-size:13" +
            ".5pt;line-height:115%;font-family:&quot;Times New Roman&quot;\" \r\n               " +
            " color=\"Black\">&nbsp;Посылки (кроме EMS) с начисленными таможенными платежами бу" +
            "дут вручаться в отделениях почтовой связи зоны обслуживания после уплаты начисле" +
            "нных платежей. </font>\r\n    <p style=\"margin-left: 250px; width: 811px;\">\r\n     " +
            "   \r\n\t\t    <font  style=\"font-size:13.5pt;line-height:115%;font-family:&quot;Tim" +
            "es New Roman&quot;\" \r\n                color=\"Black\">&nbsp;Отправления международ" +
            "ной ускоренной почты EMS недоставленные, а так же с начисленными таможенными пла" +
            "тежами, вручаются централизованно в выделенных объектах почтовой связи. </font>\r" +
            "\n    <p style=\"margin-left: 250px; width: 811px;\">\r\n        \r\n\t\t    <font  style" +
            "=\"font-size:13.5pt;line-height:115%;font-family:&quot;Times New Roman&quot;\" \r\n " +
            "               color=\"Black\">&nbsp;Информируем Вас, что в разделе «Слежение за п" +
            "очтовыми отправлениями» отображается прохождение (обмен) электронной информации " +
            "по регистрируемым почтовым отправлениям между объектами почтовой связи. Отобража" +
            "емые сведения на сайте РУП «Белпочта» носят информационный характер. </font>\r\n  " +
            "  \r\n    \r\n    <!-- Yandex.Metrika counter -->\r\n<script type=\"text/javascript\">\r\n" +
            "    (function (d, w, c) {\r\n        (w[c] = w[c] || []).push(function() {\r\n      " +
            "      try {\r\n                w.yaCounter33628179 = new Ya.Metrika({\r\n           " +
            "         id:33628179,\r\n                    clickmap:true,\r\n                    t" +
            "rackLinks:true,\r\n                    accurateTrackBounce:true\r\n                }" +
            ");\r\n            } catch(e) { }\r\n        });\r\n\r\n        var n = d.getElementsByTa" +
            "gName(\"script\")[0],\r\n            s = d.createElement(\"script\"),\r\n            f =" +
            " function () { n.parentNode.insertBefore(s, n); };\r\n        s.type = \"text/javas" +
            "cript\";\r\n        s.async = true;\r\n        s.src = \"https://mc.yandex.ru/metrika/" +
            "watch.js\";\r\n\r\n        if (w.opera == \"[object Opera]\") {\r\n            d.addEvent" +
            "Listener(\"DOMContentLoaded\", f, false);\r\n        } else { f(); }\r\n    })(documen" +
            "t, window, \"yandex_metrika_callbacks\");\r\n</script>\r\n<noscript><div><img src=\"htt" +
            "ps://mc.yandex.ru/watch/33628179\" style=\"position:absolute; left:-9999px;\" alt=\"" +
            "\" /></div></noscript>\r\n<!-- /Yandex.Metrika counter -->\r\n\r\n</body>\r\n</html>\r\n")]
        public string ResponseSample {
            get {
                return ((string)(this["ResponseSample"]));
            }
            set {
                this["ResponseSample"] = value;
            }
        }
    }
}
